#!/bin/bash

### lartf - converte arquivos em LaTeX para rtf
#
### Copyleft 2009 - Bruno C. Vellutini | http://organelas.com
#
### Pré-requisitos:
#	Pacotes latex2rtf e recode instalados
#
### Função:
#	Converter arquivos .tex para latin1 e usar o latex2rtf para convertê-los para rtf

# Verifica se a pasta "rtf" existe
# Nela que serão copiados os arquivos .tex e criado o RTF

folder=rtf
backups=backups

# Verificando se existe um diretório de backups

if [ ! -d "$backups" ]
then
	echo "no backup folder!"
	echo "creating a folder for backups..."
	mkdir $backups
fi

# Criar o backup do diretório

if [ -d "$folder" ]
then
	echo "backup folder exist!"
	echo "moving backup files..."
	tar -pczf backups/$folder"-old-"`date +%Y-%m-%d_%H%M`.tar.gz $folder/*
else
	echo "rtf folder does not exist!"
	echo "creating a folder for the LATEX -> RTF conversion..."
	mkdir $folder
fi

for i in *.tex; do
cp $i $folder/$i;
done

for i in $folder/*.tex; do
recode utf8..latin1 $i;
done

latex2rtf $folder/mestrado.tex

# Descomente a linha abaixo s quiser que o arquivo seja aberto automaticamente pelo openoffice
# ooffice $folder/mestrado.rtf

########################################

# To-Dos
# 	- Comando com argumentos, para selecionar o arquivo tex master para compilar
# 	- Colocar opção para abrir o rtf imediatamente após criação (default é o do sistema, colocar jeito de alterar)
# 	- Avançado: colocar possibilidade de alterar o comando conversor


