#!/bin/bash

### lartf - converte arquivos em LaTeX para rtf
#
### Copyleft 2009 - Bruno C. Vellutini | http://organelas.com
#
### Pacotes necessários:
#
#	latex2rtf
#	recode
#	tar
#
### Função:
#
#	Converter arquivos .tex para latin1 e usar o latex2rtf para convertê-los para rtf

# Defina as pastas
pasta=rtf
backups=backups


# Verifica se a pasta "rtf" existe
# Nela que serão copiados os arquivos .tex e criado o RTF

if [ ! -d "$pasta" ]
then
	echo "pasta rtf não existe!"
	echo "criando uma pasta para a conversão LaTeX -> RTF..."
	mkdir $pasta
fi

# Verificando se existe um diretório de backups
# Se existir já é feito o backup dos arquivos antigos
if [ ! -d "$backups" ]
then
	echo "não existe uma pasta para backup!"
	echo "criando uma pasta para backups..."
	mkdir $backups
else
	echo "pasta para backups encontrada!"
	echo "movendo os arquivos de backup..."
	tar -pczf backups/$pasta"-old-"`date +%Y-%m-%d_%H%M`.tar.gz $pasta/*
	rm -f $pasta/*
fi

# Copia os arquivos .tex para a pasta
for i in *.tex; do
cp $i $pasta/$i;
done

# Recodifica os arquivos para que o latex2rtf funcione corretamente
for i in $pasta/*.tex; do
recode utf8..latin1 $i;
done

# Realiza a conversão LaTeX -> RTF
#echo "latex2rtf $pasta/mestrado.tex"
latex2rtf $pasta/mestrado.tex

# Descomente a linha abaixo s quiser que o arquivo seja aberto automaticamente pelo openoffice
# ooffice $pasta/mestrado.rtf

########################################

# To-Dos
# 	- Comando com argumentos, para selecionar o arquivo tex master para compilar
# 	- Colocar opção para abrir o rtf imediatamente após criação (default é o do sistema, colocar jeito de alterar)
# 	- Avançado: colocar possibilidade de alterar o comando conversor
